<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="UpdateEventTimestampWithSystemTime" Id="{c08aa161-6155-4a81-a4a8-608653ecafc6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION UpdateEventTimestampWithSystemTime
VAR_INPUT
	stEvent: REFERENCE TO ST_Event;
END_VAR
VAR
	fbGETSYSTEMTIME: GETSYSTEMTIME;
	stFileTime: T_FILETIME;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbGETSYSTEMTIME(timeLoDW=> stFileTime.dwLowDateTime,
				timeHiDW=> stFileTime.dwHighDateTime);
stEvent.dtTimestamp := FILETIME_TO_DT(fileTime := stFileTime);
	
				]]></ST>
    </Implementation>
    <LineIds Name="UpdateEventTimestampWithSystemTime">
      <LineId Id="7" Count="0" />
      <LineId Id="12" Count="0" />
      <LineId Id="14" Count="0" />
      <LineId Id="16" Count="0" />
      <LineId Id="15" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>