<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_PressureSensor" Id="{17567b52-9a99-4ecd-ac02-8e7eeae25c38}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_PressureSensor
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	rPressure : REAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="getPressure" Id="{a745bce9-e7b1-4e02-b18e-265bce1f8258}">
      <Declaration><![CDATA[PROPERTY getPressure : REAL]]></Declaration>
      <Get Name="Get" Id="{d653a4e6-8290-4a1d-af67-b1bc9a168e9b}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[getPressure := rPressure;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <LineIds Name="FB_PressureSensor">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_PressureSensor.getPressure.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>