<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{1c5099ca-8ba9-4952-97a3-dfd211cf5f06}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	bIn : BOOL;
	bOut : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[bIn := GVL.bIn;

GVL.bOut := bOut;
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="9" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="17" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>