<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Test2" Id="{b386e113-997f-4246-baf7-74a116b1bd17}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Test2
VAR_INPUT
		i: INT;
END_VAR
VAR_OUTPUT
END_VAR
VAR

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Test2">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>