<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{2ff7b83e-9d69-4049-8b2d-19c87bd75e82}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR

	rL
	i : INT;			//[0..100]%
	bNeg : BOOL;
	bPos : BOOL;
	berror : BOOL;
	lrTest : LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
			]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="70" Count="0" />
      <LineId Id="61" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>