<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{c474b279-45ae-49a1-aa1e-ee0327b7f910}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	iTest : UINT;
	
	
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[iTest := GVL.iTest;


	 ]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="58" Count="0" />
      <LineId Id="54" Count="0" />
      <LineId Id="53" Count="0" />
      <LineId Id="20" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>