<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Test2" Id="{9bb125dd-180d-4b92-9e89-4d1b14905139}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Test2
VAR_INPUT
	bTest : INT;
END_VAR
VAR_OUTPUT
	bOut : INT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[bOut := 2*bTest;]]></ST>
    </Implementation>
    <LineIds Name="FB_Test2">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>