<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{53c863e0-dbf2-43aa-ba37-9c40920ffee2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbTest : FB_Test;
	
	bActivate : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbTest();

fbTest.Prop := bActivate;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="15" Count="1" />
      <LineId Id="13" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>