<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TEST" Id="{6cabfc6a-b673-4936-9b06-43f4016d3a05}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM TEST
VAR
	fbTest : FB_Test;
	
	i : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[i := fbTest.Prop;]]></ST>
    </Implementation>
    <LineIds Name="TEST">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>