<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{62e43a78-46c8-44c8-9f1f-e8406f48095f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbDistanceSensor : FB_DistanceSensor;
	
	fDistance : LREAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbDistanceSensor();
fDistance := fbDistanceSensor.fDistance;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="293" Count="0" />
      <LineId Id="261" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>