<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="BackgroundRS232" Id="{a474ab24-92b2-4faa-ab36-f1eb12602ab9}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM BackgroundRS232
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[BackgroundEL6001();]]></ST>
    </Implementation>
    <LineIds Name="BackgroundRS232">
      <LineId Id="13" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>