<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_BoxLED" Id="{55242ab5-9ff4-4666-b1b6-38e99286d969}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_BoxLED
VAR_INPUT
END_VAR
VAR_OUTPUT
	eCondition : eConditionCheck;
END_VAR
VAR
	eLEDMode : eLightMode;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
]]></ST>
    </Implementation>
    <Property Name="setLightMode" Id="{8039be3d-e687-4f0b-a7ec-3b99ee8a857e}">
      <Declaration><![CDATA[PROPERTY setLightMode : eLightMode]]></Declaration>
      <Set Name="Set" Id="{ab54af1d-7396-4390-94b5-279c607d86d7}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[eLEDMode := setLightMode;]]></ST>
        </Implementation>
      </Set>
    </Property>
    <LineIds Name="FB_BoxLED">
      <LineId Id="11" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_BoxLED.setLightMode.Set">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>